server:
  port: 9008
spring:
  application:
    name: cloud-config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  cloud:
#    bus:
#      trace:
#        enabled: true## 开启消息跟踪    （暂时没用）
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh