server:
  port: 9004
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/LuckLarry/spring-config-server-training
          search-paths: config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#username:
#password: 如果是公有github库就不需要账号和密码
#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
#git配置更新后，访问对应的地址，就会把配置信息发送到对应的项目里面
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh