server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:9000/eureka/
spring:
  application:
    name: eureka-server