server:
  port: 5001
spring:
  application:
    name: spring-cloud-swagger2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
swagger:
  base-package: springcloudswagger2
