spring:
  application:
    name: spring-cloud-gateway-zuul
server:
  port: 9006
zuul:
  routes:
    baidu:
      path: /it/**
      url: http://www.ityouknow.com/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

